// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZ1zbW7Jm0ruoX54wOfVOBwJTbEbhK_Q',
    appId: '1:775065999324:web:23d8c85773f5f290abe119',
    messagingSenderId: '775065999324',
    projectId: 'psga-app-123',
    authDomain: 'psga-app-123.firebaseapp.com',
    storageBucket: 'psga-app-123.firebasestorage.app',
    measurementId: 'G-MRPHEY28H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CyEwgXZJX3Z197-4TAYd3tXoB4bggYE',
    appId: '1:775065999324:android:ce9bb7656f0d78deabe119',
    messagingSenderId: '775065999324',
    projectId: 'psga-app-123',
    storageBucket: 'psga-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXEqUd9y-lMN_wyHdAi-sExlwhG_q-7sE',
    appId: '1:775065999324:ios:a495be762bccc296abe119',
    messagingSenderId: '775065999324',
    projectId: 'psga-app-123',
    storageBucket: 'psga-app-123.firebasestorage.app',
    iosBundleId: 'com.example.psgaApp',
  );
}
