platform :ios, '14.0'

# تأكد من استيراد ملف الإعدادات التلقائي
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # هذه السطور هي المسؤولة عن جلب إضافات فلاتر تلقائياً
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # إجبار جميع المكتبات على استخدام iOS 14
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end