# السطر التالي ضروري جداً لتعريف وظائف فلاتر داخل الـ Podfile
pattern = File.join('..', 'Flutter', 'generated_plugin_registrant.rb')
require File.expand_path(pattern, __FILE__)

# تحديد المنصة المطلوبة لمكتبة الخرائط
platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # سحب الإضافات (Plugins) تلقائياً
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # إجبار جميع المكتبات على استخدام iOS 14 لتجنب أي تعارض
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end